### ISSUE TITLE
24 hour format

### ISSUE THREAD

**Issue by TheLion** [pablogventura/Octoprint-ETA#11]
Although my timezone and locales information is set correctly in Raspbian, Octoprint-ETA displays the ETA in AM/PM format.

**Comment by AlexVerrico** [comment]
Hi Everyone.
I know that this issue is an old one, but just for anyone who finds it, I have added this functionality after taking over maintenance of the plugin. See https://github.com/AlexVerrico/Octoprint-Display-ETA
Cheers,
Alex.

**Comment by TheLion** [comment]
This issue has been solved by the AlexVerrico version of this plugin. See [https://github.com/AlexVerrico/Octoprint-Display-ETA](https://github.com/AlexVerrico/Octoprint-Display-ETA)
