### ISSUE TITLE
am / pm

### ISSUE THREAD

**Issue by halfluck** [pablogventura/Octoprint-ETA#2]
This is Great, thanks for your time and effort and releasing this plugin.,

I'd like to see an am/pm next to the numbers, so that it stands out that it is infact Time of Day.

Thanks Rob.

**Comment by pablogventura** [comment]
Thank you very much for your return! That's a great idea!
Soon I will add support to print the time in local format, depending on the locale configured on the host.

**Comment by pablogventura** [comment]
The new version with support for AM/PM is ready! 😄 
If Octoprint does not offer to update, please uninstall the plugin and reinstall it.
Any other comments are welcome!
